# ~/.bashrc
# Generated by Gemini CLI

# --- 1. BLE.SH (Must be first) ---
# Autosuggestions, syntax highlighting, and vim mode
[[ -f ~/.local/share/blesh/ble.sh ]] && source ~/.local/share/blesh/ble.sh

# --- 2. ENVIRONMENT ---
export TERM="xterm-256color"
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"
export EDITOR="lvim"
export LESS="-R"

# --- 3. PATH CONFIGURATION ---
# Helper to cleanly prepend to PATH
prepend_path() {
    [ -d "$1" ] && export PATH="$1:$PATH"
}

# Base Paths (Homebrew first)
export PATH="/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:$HOME/go/bin:$HOME/.cargo/bin:$PATH"

# Android
export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
prepend_path "$ANDROID_SDK_ROOT/platform-tools"
prepend_path "$ANDROID_SDK_ROOT/tools/bin"
prepend_path "/Library/Android/bin"

# Java
# export JAVA_HOME=$(/usr/libexec/java_home)

# .NET
export DOTNET_ROOT="/usr/local/share/dotnet/x64"
prepend_path "$DOTNET_ROOT"
prepend_path "$HOME/.dotnet/tools"
prepend_path "/Applications/Rider.app/Contents/MacOS"

# Node/NPM
export NODE_PATH="$HOME/node_modules:/usr/local/lib/node_modules"

# Go
export GOPATH="$HOME/go"
prepend_path "$GOPATH/bin"

# OpenAI
if [ -f ~/.bashrc.secrets ]; then source ~/.bashrc.secrets; fi

# Custom
prepend_path "$HOME/code/Ev2/Ev2_CLI/Mac"
prepend_path "$HOME/.antigravity/antigravity/bin"

# --- 4. TOOL INITIALIZATION ---

# Starship (Prompt)
eval "$(starship init bash)"

# FZF (Fuzzy Finder)
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
# Use fd/rg for fzf if available (faster than find)
if command -v fd > /dev/null; then
  export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix --hidden --follow --exclude .git'
fi

# Bash Completion (Homebrew)
if [[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]]; then
  . "/opt/homebrew/etc/profile.d/bash_completion.sh"
fi

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
prepend_path "$PYENV_ROOT/bin"
if command -v pyenv >/dev/null; then
  eval "$(pyenv init -)"
fi

# Nodenv
if command -v nodenv >/dev/null; then
  eval "$(nodenv init -)"
fi

# Direnv
if command -v direnv >/dev/null; then
  eval "$(direnv hook bash)"
fi

# Zoxide (Better z command)
if command -v zoxide >/dev/null; then
  eval "$(zoxide init bash)"
fi

# --- 5. ALIASES ---

# Basics
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ls='ls -G' # Colorized ls on macOS
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias vi="lvim"
alias vim="lvim"
alias lg="lazygit"
alias nuget="dotnet nuget"

# Kubernetes
alias kc="kubectl"

# Bard
alias b="bard-cli"
alias bi="bard-cli -i"

# Git (Standard + Lazy)
alias g="git"
alias gpr="git pull --rebase"
alias gco="git checkout"
alias gcod="git checkout develop" # Assuming this is what 'cod' meant
alias gfo="git fetch origin"
alias gst="git status"

# Amazon / Brazil
alias nds="ninja-dev-sync"
alias bb="brazil-build"
alias bbb="brazil-build build"
alias b3="brazil-build build"
alias bbr="brazil-build release"
alias bbt="brazil-build test"
alias bbf="brazil-build format-fix"
alias bbl="brazil-build lint-fix"
alias bbu="brazil-build single-unit-test"
alias bbc="brazil-build clean"
alias bbcb="brazil-build clean ; brazil-build"
alias bbcr="brazil-build clean ; brazil-build release"
alias brc="brazil-recursive-cmd"
alias brc_all="brc \"brazil-build clean && brazil-build\" --all "
alias bws="brazil ws"
alias sam="brazil-build-tool-exec sam"

alias wat="watson"
alias wats="watson start"
alias watr="watson stop"
alias waps="wats ap-support"

alias sdkmanager="sdkmanager --sdk_root=/Library/Android"

# Credentials (Pasted from fish config)
alias pp-alpha-credentials="ada cred update --account=513982291898 --provider=conduit --role=IibsAdminAccess-DO-NOT-DELETE"
alias pp-beta-credentials="ada cred update --account=292966146994 --provider=conduit --role=IibsAdminAccess-DO-NOT-DELETE"
alias pp-gamma-credentials="ada cred update --account=345605054930 --provider=conduit --role=IibsAdminAccess-DO-NOT-DELETE"
alias pp-prod-credentials="ada cred update --account=768783451950 --provider=conduit --role=IdentityOncallReadOnly"
alias hpcs-alpha-credentials="ada cred update --account=945261933260 --provider=conduit --role=IibsAdminAccess-DO-NOT-DELETE"
alias hpcs-beta-credentials="ada cred update --account=471937419820 --provider=conduit --role=IibsAdminAccess-DO-NOT-DELETE"
alias hpcs-gamma-credentials="ada cred update --account=272237724837 --provider=conduit --role=IibsAdminAccess-DO-NOT-DELETE"
alias hpcs-prod-credentials="ada cred update --account=186476458307 --provider=conduit --role=IibsAdminAccess-DO-NOT-DELETE"

# Functions
notify() {
    osascript -e 'display notification "😎" with title "Process Finished"'
    say -v Samantha "process finished"
}

# --- 6. HISTORY CONFIG ---
export HISTCONTROL=ignoreboth:erasedups  # no duplicate entries
export HISTSIZE=100000                   # big history
export HISTFILESIZE=100000               # big history file
shopt -s histappend                      # append to history, don't overwrite
